import { StyleSheet } from 'react-native';
import { colors } from '@/theme';

export const registrationStyles = StyleSheet.create({
  twoColumns: { flexDirection: 'row', gap: 10 },
  column: { flex: 1 },
  dateButton: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  dateText: { color: colors.text, fontSize: 15, fontWeight: '700' },
  datePlaceholder: { color: colors.muted, fontWeight: '400' },
  calculationCard: {
    flexDirection: 'row',
    gap: 9,
    padding: 13,
    borderRadius: 15,
    backgroundColor: colors.purple,
  },
  calculationItem: { flex: 1 },
  calculationLabel: { color: colors.muted, fontSize: 9, fontWeight: '700' },
  calculationValue: {
    marginTop: 3,
    color: colors.primaryDark,
    fontSize: 14,
    fontWeight: '900',
  },
  calculationDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
  },
  choiceRow: { flexDirection: 'row', gap: 10 },
  choice: {
    flex: 1,
    minHeight: 67,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  choiceActive: { borderColor: colors.primary, backgroundColor: colors.pink },
  choiceLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  choiceLabelActive: { color: colors.primaryDark },
  consentCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 11,
    padding: 15,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  consentCardActive: {
    borderColor: colors.primary,
    backgroundColor: '#FFF8FB',
  },
  checkbox: {
    width: 23,
    height: 23,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  checkboxActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  consentCopy: { flex: 1, gap: 4 },
  consentTitle: { color: colors.text, fontSize: 12, fontWeight: '800' },
  consentText: { color: colors.muted, fontSize: 10, lineHeight: 16 },
  helperNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.blue,
  },
  helperText: { flex: 1, color: colors.muted, fontSize: 9, lineHeight: 14 },
});
