import { StyleSheet } from 'react-native';
import { colors } from '@/theme';

export const researcherStyles = StyleSheet.create({
  pageHeading: { gap: 5 },
  pageEyebrowRow: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  pageIconBox: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink,
  },
  pageIconText: { color: colors.primaryDark, fontSize: 13, fontWeight: '900' },
  pageEyebrow: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  pageTitle: { color: colors.text, fontSize: 29, fontWeight: '900' },
  pageSubtitle: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  sectionLabel: { color: colors.text, fontSize: 13, fontWeight: '800' },
  sectionTitle: { color: colors.text, fontSize: 19, fontWeight: '900' },
  sectionHint: { marginTop: 2, color: colors.muted, fontSize: 11 },
  listHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  countPill: {
    minWidth: 34,
    height: 28,
    paddingHorizontal: 9,
    borderRadius: 99,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink,
  },
  countPillText: { color: colors.primaryDark, fontSize: 12, fontWeight: '900' },

  searchPanel: {
    gap: 12,
    padding: 15,
    borderRadius: 19,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  clearFilterText: { color: colors.primary, fontSize: 12, fontWeight: '800' },
  filterWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 99,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  filterChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  filterChipText: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  filterChipTextActive: { color: 'white' },
  respondentList: {
    paddingHorizontal: 15,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  respondentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 15,
  },
  listRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  respondentAvatar: {
    width: 45,
    height: 45,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink,
  },
  respondentAvatarText: {
    color: colors.primaryDark,
    fontSize: 14,
    fontWeight: '900',
  },
  respondentContent: { flex: 1, gap: 7 },
  respondentNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  respondentName: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  respondentProgressText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
  },
  respondentMeta: { color: colors.muted, fontSize: 11 },
  respondentStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  videoCountText: { color: colors.muted, fontSize: 10, fontWeight: '700' },
  rowChevron: { color: colors.primary, fontSize: 26, fontWeight: '300' },
  paginationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    paddingVertical: 4,
  },
  paginationButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  paginationDisabled: { opacity: 0.32 },
  paginationButtonText: {
    color: colors.primaryDark,
    fontSize: 25,
    lineHeight: 28,
  },
  paginationLabel: { minWidth: 88, alignItems: 'center' },
  paginationCurrent: { color: colors.text, fontSize: 13, fontWeight: '800' },
  paginationTotal: { color: colors.muted, fontSize: 10 },
  emptyState: {
    alignItems: 'center',
    gap: 9,
    padding: 24,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyStateIcon: {
    width: 54,
    height: 54,
    marginBottom: 3,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateIconText: {
    color: colors.primaryDark,
    fontSize: 23,
    fontWeight: '900',
  },
  emptyStateTitle: { color: colors.text, fontSize: 16, fontWeight: '900' },
  emptyStateText: {
    maxWidth: 280,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },

  monitoringHero: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderRadius: 21,
    backgroundColor: colors.primaryDark,
  },
  monitoringHeroCopy: { flex: 1 },
  monitoringHeroEyebrow: {
    color: '#EFCFDE',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  monitoringHeroValue: { color: 'white', fontSize: 36, fontWeight: '900' },
  monitoringHeroHint: {
    maxWidth: 210,
    color: '#EAD9E1',
    fontSize: 11,
    lineHeight: 16,
  },
  monitoringHeroBadge: {
    width: 67,
    height: 67,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.13)',
  },
  monitoringHeroBadgeValue: { color: 'white', fontSize: 23, fontWeight: '900' },
  monitoringHeroBadgeLabel: { color: '#EAD9E1', fontSize: 10 },
  monitoringCard: {
    gap: 15,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  monitoringCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  videoNumberBox: {
    width: 48,
    height: 52,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.blue,
  },
  videoNumberEyebrow: {
    color: colors.muted,
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  videoNumberValue: {
    color: colors.primaryDark,
    fontSize: 21,
    fontWeight: '900',
  },
  monitoringTitleWrap: { flex: 1, gap: 3 },
  monitoringTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  monitoringCohort: { color: colors.muted, fontSize: 10 },
  stageGrid: { flexDirection: 'row', gap: 6 },
  stageItem: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  stageDot: { width: 6, height: 6, borderRadius: 3 },
  stageValue: { color: colors.text, fontSize: 16, fontWeight: '900' },
  stageLabel: { color: colors.muted, fontSize: 8 },
  stageProgressTrack: {
    height: 6,
    borderRadius: 99,
    overflow: 'hidden',
    backgroundColor: '#EEE8EB',
  },
  stageProgressFill: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: colors.success,
  },
  stageProgressText: { color: colors.muted, fontSize: 10, textAlign: 'right' },

  resultHero: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 18,
    borderRadius: 21,
    backgroundColor: colors.primaryDark,
  },
  resultHeroEyebrow: {
    color: '#EFCFDE',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  resultHeroScoreRow: { flexDirection: 'row', alignItems: 'baseline' },
  resultHeroScore: { color: 'white', fontSize: 39, fontWeight: '900' },
  resultHeroScale: { color: '#EAD9E1', fontSize: 14, fontWeight: '700' },
  resultHeroHint: { color: '#EAD9E1', fontSize: 10 },
  resultHeroBadge: {
    width: 65,
    height: 65,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  resultHeroBadgeValue: { color: 'white', fontSize: 22, fontWeight: '900' },
  resultHeroBadgeLabel: { color: '#EAD9E1', fontSize: 9 },
  resultCard: {
    gap: 14,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  resultCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  resultVideoNumber: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink,
  },
  resultVideoNumberText: {
    color: colors.primaryDark,
    fontSize: 15,
    fontWeight: '900',
  },
  resultTitleWrap: { flex: 1, gap: 2 },
  resultTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 19,
  },
  resultSubtitle: { color: colors.muted, fontSize: 9 },
  scoreBadge: {
    minWidth: 59,
    alignItems: 'center',
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRadius: 13,
  },
  scoreBadgeValue: {
    color: colors.primaryDark,
    fontSize: 18,
    fontWeight: '900',
  },
  scoreBadgeLabel: { color: colors.muted, fontSize: 7 },
  scoreProgressTrack: {
    height: 7,
    borderRadius: 99,
    overflow: 'hidden',
    backgroundColor: '#EEE8EB',
  },
  scoreProgressFill: { height: '100%', borderRadius: 99 },
  scoreStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 2,
  },
  scoreStat: { flex: 1, alignItems: 'center', gap: 2 },
  scoreStatValue: { color: colors.text, fontSize: 15, fontWeight: '900' },
  scoreStatLabel: { color: colors.muted, fontSize: 9 },
  scoreStatDivider: {
    width: StyleSheet.hairlineWidth,
    height: 27,
    backgroundColor: colors.border,
  },

  comparisonHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 18,
    borderRadius: 21,
    backgroundColor: '#245E49',
  },
  comparisonHeroIcon: {
    width: 57,
    height: 57,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  comparisonHeroIconText: { color: 'white', fontSize: 27, fontWeight: '900' },
  comparisonHeroCopy: { flex: 1 },
  comparisonHeroEyebrow: {
    color: '#CDE9DC',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  comparisonHeroValue: { color: 'white', fontSize: 32, fontWeight: '900' },
  comparisonHeroHint: { color: '#CDE9DC', fontSize: 10, lineHeight: 15 },
  comparisonCard: {
    gap: 15,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  comparisonCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  changePill: {
    minWidth: 48,
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 99,
    backgroundColor: '#DDF4E8',
  },
  changePillText: { color: colors.success, fontSize: 12, fontWeight: '900' },
  beforeAfterRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  scoreComparison: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
    paddingVertical: 13,
    borderRadius: 15,
    backgroundColor: colors.purple,
  },
  scoreComparisonLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
  },
  scoreComparisonValue: {
    color: colors.primaryDark,
    fontSize: 23,
    fontWeight: '900',
  },
  comparisonArrow: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  comparisonArrowText: { color: colors.primary, fontSize: 17 },
  improvementMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 12,
    backgroundColor: '#F4FAF7',
  },
  improvementMessageIcon: {
    color: colors.success,
    fontSize: 15,
    fontWeight: '900',
  },
  improvementMessageText: { flex: 1, color: colors.muted, fontSize: 11 },
  noDataText: {
    padding: 10,
    borderRadius: 12,
    color: colors.muted,
    fontSize: 10,
    textAlign: 'center',
    backgroundColor: colors.background,
  },

  exportStepHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    marginTop: 4,
  },
  stepNumber: {
    width: 31,
    height: 31,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  stepNumberText: { color: 'white', fontSize: 13, fontWeight: '900' },
  datasetList: {
    paddingHorizontal: 14,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  datasetOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  datasetOptionActive: { backgroundColor: '#FFF8FB' },
  datasetIcon: {
    width: 39,
    height: 39,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple,
  },
  datasetIconText: {
    color: colors.primaryDark,
    fontSize: 14,
    fontWeight: '900',
  },
  datasetCopy: { flex: 1, gap: 3 },
  datasetTitle: { color: colors.text, fontSize: 13, fontWeight: '800' },
  datasetDescription: { color: colors.muted, fontSize: 9, lineHeight: 14 },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  radioOuterActive: { borderColor: colors.primary },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  filterPanel: {
    gap: 12,
    padding: 15,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  formLabel: { color: colors.text, fontSize: 12, fontWeight: '800' },
  numberChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  numberChip: {
    minWidth: 35,
    height: 35,
    paddingHorizontal: 9,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  numberChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  numberChipText: { color: colors.muted, fontSize: 11, fontWeight: '800' },
  numberChipTextActive: { color: 'white' },
  dateFields: { flexDirection: 'row', gap: 10 },
  dateField: { flex: 1 },
  exportSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 17,
    backgroundColor: colors.purple,
  },
  exportSummaryIcon: {
    width: 43,
    height: 43,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  exportSummaryIconText: {
    color: colors.primaryDark,
    fontSize: 10,
    fontWeight: '900',
  },
  exportSummaryCopy: { flex: 1, gap: 3 },
  exportSummaryTitle: { color: colors.text, fontSize: 13, fontWeight: '900' },
  exportSummaryText: { color: colors.muted, fontSize: 9, lineHeight: 14 },
  securityNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 14,
    borderRadius: 17,
    backgroundColor: colors.blue,
  },
  securityNoteIcon: {
    color: colors.primaryDark,
    fontSize: 20,
    fontWeight: '900',
  },
  securityNoteTitle: { color: colors.text, fontSize: 12, fontWeight: '800' },
  securityNoteText: {
    marginTop: 2,
    color: colors.muted,
    fontSize: 10,
    lineHeight: 15,
  },

  // Existing respondent-detail and compatibility styles.
  cardTitle: { fontSize: 17, fontWeight: '800', color: colors.text },
  score: { fontSize: 34, fontWeight: '900', color: colors.primary },
  timeline: { flexDirection: 'row', gap: 12 },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
    marginTop: 5,
  },
  improvement: { fontSize: 18, fontWeight: '900' },
  filter: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  choice: {
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  choiceActive: { borderColor: colors.primary, backgroundColor: colors.pink },
});
