import { StyleSheet } from 'react-native';
import { colors } from '@/theme';

export const respondentStyles = StyleSheet.create({
  cardTitle: { fontSize: 17, fontWeight: '800', color: colors.text },

  testIntroHeading: { gap: 8 },
  testTypePill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 99,
    backgroundColor: colors.purple,
  },
  testTypePillText: {
    color: colors.primaryDark,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.9,
  },
  testIntroTitle: { color: colors.text, fontSize: 30, fontWeight: '900' },
  testIntroSubtitle: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  testIntroHero: {
    borderRadius: 22,
    backgroundColor: colors.primaryDark,
  },
  testIntroHeroPretest: {
    minHeight: 188,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    padding: 18,
  },
  testIntroHeroPosttest: {
    alignItems: 'center',
    paddingVertical: 23,
  },
  testIntroHeroVisual: {
    width: 124,
    height: 148,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'flex-end',
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.13)',
  },
  testIntroHeroIcon: {
    width: 49,
    height: 49,
    marginBottom: 8,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  testIntroHeroImage: {
    width: 94,
    height: 142,
  },
  testIntroHeroSummary: {
    flex: 1,
    alignItems: 'flex-start',
  },
  testIntroHeroKicker: {
    marginBottom: 8,
    color: colors.pink,
    fontSize: 12,
    fontWeight: '800',
  },
  testIntroHeroValue: { color: 'white', fontSize: 42, fontWeight: '900' },
  testIntroHeroLabel: {
    marginTop: -3,
    color: colors.surface,
    fontSize: 14,
    fontWeight: '800',
  },
  testIntroHeroDuration: { marginTop: 8, color: colors.pink, fontSize: 11 },
  instructionCard: {
    paddingHorizontal: 15,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  instructionTitle: {
    paddingTop: 15,
    paddingBottom: 4,
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
  },
  instructionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingVertical: 12,
  },
  instructionBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  instructionNumber: {
    width: 31,
    height: 31,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink,
  },
  instructionNumberText: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: '900',
  },
  instructionCopy: { flex: 1, gap: 2 },
  instructionRowTitle: { color: colors.text, fontSize: 12, fontWeight: '800' },
  instructionDescription: { color: colors.muted, fontSize: 9, lineHeight: 14 },
  testNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 13,
    borderRadius: 15,
    backgroundColor: colors.blue,
  },
  testNoticeText: {
    flex: 1,
    color: colors.muted,
    fontSize: 10,
    lineHeight: 15,
  },

  testHeader: {
    gap: 10,
    padding: 15,
    borderRadius: 19,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  testHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  testHeaderEyebrow: {
    color: colors.primary,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1,
  },
  testHeaderTitle: {
    marginTop: 2,
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
  },
  answeredPill: {
    minWidth: 48,
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 99,
    backgroundColor: colors.pink,
  },
  answeredPillText: {
    color: colors.primaryDark,
    fontSize: 11,
    fontWeight: '900',
  },
  testHeaderHint: { color: colors.muted, fontSize: 9, textAlign: 'right' },
  questionCard: {
    gap: 14,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  questionHeading: { flexDirection: 'row', alignItems: 'flex-start', gap: 11 },
  questionNumber: {
    width: 32,
    height: 32,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryDark,
  },
  questionNumberText: { color: 'white', fontSize: 12, fontWeight: '900' },
  questionText: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 21,
  },
  optionList: { gap: 8 },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 52,
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  optionSelected: { backgroundColor: '#FFF4F8', borderColor: colors.primary },
  optionLetterBox: {
    width: 31,
    height: 31,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple,
  },
  optionLetterBoxSelected: { backgroundColor: colors.primary },
  optionLetter: { color: colors.primaryDark, fontSize: 11, fontWeight: '900' },
  optionText: { flex: 1, color: colors.text, fontSize: 12, lineHeight: 17 },
  optionTextSelected: { color: colors.primaryDark, fontWeight: '700' },
  optionRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  optionRadioSelected: { borderColor: colors.primary },
  optionRadioDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  submitCard: {
    gap: 12,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.purple,
  },
  submitCopy: { gap: 2 },
  submitTitle: { color: colors.text, fontSize: 14, fontWeight: '900' },
  submitHint: { color: colors.muted, fontSize: 9 },

  video: {
    width: '100%',
    aspectRatio: 16 / 9,
    backgroundColor: '#171217',
    borderRadius: 18,
    overflow: 'hidden',
  },
});
