import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import * as FileSystem from 'expo-file-system/legacy'; import * as Sharing from 'expo-sharing';
import { api } from '../../services/api'; import { useSession } from '../../services/session'; import { Badge, Button, Card, Field, Loading, Notice, Progress, Screen, Title, ui } from '../../components/ui'; import { colors } from '../../theme';

export function ResearcherHome(){const q=useQuery({queryKey:['researcher-overview'],queryFn:()=>api<any>('/researcher/overview')});if(q.isLoading)return <Screen><Loading/></Screen>;const d=q.data??{};const menus=[['Responden','/researcher/respondents'],['Monitoring Video','/researcher/video-monitoring'],['Hasil Pretest','/researcher/pretest-results'],['Hasil Posttest','/researcher/posttest-results'],['Perbandingan','/researcher/comparison'],['Ekspor Data','/researcher/export']];return <Screen><Title subtitle="Ringkasan terbaru pelaksanaan penelitian.">Dasbor Peneliti</Title>{q.error&&<Notice>{q.error.message}</Notice>}<View style={s.grid}><Summary label="Total responden" value={d.totalRespondents??0}/><Summary label="Aktif" value={d.activeRespondents??0}/><Summary label="Selesai 7 video" value={d.completedAllVideos??0}/><Summary label="Rata-rata progres" value={`${d.averageProgress??0}%`}/></View><Title>Menu</Title>{menus.map(([label,path])=><Card key={path} onPress={()=>router.push(path as never)}><Text style={s.cardTitle}>{label}</Text><Text style={ui.muted}>Buka rincian →</Text></Card>)}<Button variant="danger" onPress={async()=>{await useSession.getState().signOut();router.replace('/onboarding' as never)}}>Keluar</Button></Screen>}
function Summary({label,value}:{label:string;value:string|number}){return <View style={s.summary}><Text style={s.value}>{value}</Text><Text style={[ui.muted,{fontSize:13}]}>{label}</Text></View>}

export function RespondentsScreen(){const[search,setSearch]=useState('');const[submitted,setSubmitted]=useState('');const[status,setStatus]=useState('');const[page,setPage]=useState(1);const q=useQuery({queryKey:['respondents',submitted,status,page],queryFn:()=>api<any>(`/researcher/respondents?page=${page}&limit=20&search=${encodeURIComponent(submitted)}&status=${status}`)});return <Screen><Title subtitle="Cari dan saring progres individu.">Responden</Title><Field label="Cari nama" value={search} onChangeText={setSearch} returnKeyType="search" onSubmitEditing={()=>{setPage(1);setSubmitted(search)}}/><Text style={ui.label}>Status</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{[['','Semua'],['pretest_required','Pretest'],['waiting_posttest','Menunggu'],['posttest_available','Posttest'],['completed','Selesai']].map(([value,label])=><Pressable key={value} onPress={()=>{setPage(1);setStatus(value)}} style={[s.filter,status===value&&s.choiceActive]}><Text style={ui.label}>{label}</Text></Pressable>)}</View><Button variant="secondary" onPress={()=>{setPage(1);setSubmitted(search)}}>Cari</Button>{q.isLoading?<Loading/>:q.error?<Notice>{q.error.message}</Notice>:(q.data?.items?.length?q.data.items.map((r:any)=><Card key={r.id} onPress={()=>router.push(`/researcher/respondents/${r.id}` as never)}><Text style={s.cardTitle}>{r.name}</Text><Text style={ui.muted}>{r.age} tahun • HPL {date(r.hpl)}</Text><Badge>{statusLabel(r.current_status)}</Badge><Progress value={Number(r.progress_percentage)}/><Text style={ui.muted}>{r.progress_percentage}% • {r.completed_videos}/7 video</Text></Card>):<Notice>Belum ada responden yang sesuai.</Notice>)}<View style={{flexDirection:'row',gap:10}}><View style={{flex:1}}><Button variant="secondary" disabled={page<=1} onPress={()=>setPage(p=>p-1)}>Sebelumnya</Button></View><View style={{flex:1}}><Button variant="secondary" disabled={page>=(q.data?.totalPages??1)} onPress={()=>setPage(p=>p+1)}>Berikutnya</Button></View></View><Text style={[ui.muted,{textAlign:'center'}]}>Halaman {page} dari {q.data?.totalPages??1}</Text></Screen>}

export function RespondentDetail(){const{id}=useLocalSearchParams<{id:string}>();const q=useQuery({queryKey:['respondent-detail',id],queryFn:()=>api<any>(`/researcher/respondents/${id}`)});if(q.isLoading)return <Screen><Loading/></Screen>;if(q.error||!q.data)return <Screen><Notice>{q.error?.message??'Tidak ditemukan.'}</Notice></Screen>;const{profile,progress,tests,timeline}=q.data;return <Screen><Title subtitle={`Terdaftar ${dateTime(profile.created_at)}`}>{profile.name}</Title><Card>{[['Usia',`${profile.age} tahun`],['Telepon',profile.phone_number],['Alamat',profile.address],['HPL',date(profile.hpl)],['Usia kehamilan',`${profile.pregnancy_age_weeks} minggu`],['Riwayat medis',profile.medical_history||'Tidak ada'],['Riwayat komplikasi',profile.pregnancy_complication_history||'Tidak ada']].map(([a,b])=><View key={a}><Text style={ui.label}>{a}</Text><Text style={ui.muted}>{b}</Text></View>)}</Card><Title>Progres video</Title>{progress.length?progress.map((p:any)=><Card key={p.id}><Text style={s.cardTitle}>Video {p.videos.sequence_number}: {p.videos.title}</Text><Badge>{statusLabel(p.status)}</Badge><Progress value={Number(p.completion_percentage)}/><Text style={ui.muted}>{p.completion_percentage}% • maksimum {Math.floor(p.max_watched_seconds)} detik</Text></Card>):<Notice>Belum ada progres.</Notice>}<Title>Nilai tes</Title>{tests.length?tests.map((t:any)=><Card key={t.id}><Text style={s.cardTitle}>Video {t.videos.sequence_number} • {t.test_type}</Text><Text style={s.score}>{t.score}</Text><Text style={ui.muted}>{t.correct_count}/{t.total_questions} benar • {dateTime(t.submitted_at)}</Text></Card>):<Notice>Belum ada hasil tes.</Notice>}<Title>Jejak aktivitas</Title>{timeline.map((item:any,index:number)=><View key={`${item.created_at}-${index}`} style={s.timeline}><View style={s.dot}/><View style={{flex:1}}><Text style={ui.label}>{item.action.replaceAll('_',' ')}</Text><Text style={ui.muted}>{dateTime(item.created_at)}</Text></View></View>)}</Screen>}

export function MonitoringScreen(){const q=useQuery({queryKey:['video-monitoring'],queryFn:()=>api<any[]>('/researcher/videos/monitoring')});return <Screen><Title subtitle="Jumlah responden pada setiap tahap.">Monitoring Video</Title>{q.isLoading?<Loading/>:q.error?<Notice>{q.error.message}</Notice>:q.data?.map(v=><Card key={v.video_id} onPress={()=>router.push('/researcher/respondents' as never)}><Text style={s.cardTitle}>Video {v.sequence_number}: {v.title}</Text><Metric label="Pretest selesai" value={v.pretest_completed}/><Metric label="Video selesai" value={v.video_completed}/><Metric label="Menunggu posttest" value={v.waiting_posttest}/><Metric label="Posttest selesai" value={v.posttest_completed}/></Card>)}</Screen>}
function Metric({label,value}:{label:string;value:number}){return <View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={ui.muted}>{label}</Text><Text style={ui.label}>{value}</Text></View>}

export function ResultsScreen({type}:{type:'pretest'|'posttest'}){const q=useQuery({queryKey:['results',type],queryFn:()=>api<any[]>(`/researcher/results/${type}`)});return <Screen><Title subtitle="Ringkasan nilai per materi.">Hasil {type==='pretest'?'Pretest':'Posttest'}</Title>{q.isLoading?<Loading/>:q.error?<Notice>{q.error.message}</Notice>:q.data?.length?q.data.map(v=><Card key={v.video_id}><Text style={s.cardTitle}>Video {v.sequence_number}: {v.title}</Text><Text style={s.score}>{v.average_score}</Text><Text style={ui.muted}>Rata-rata • rentang {v.lowest_score}–{v.highest_score} • {v.respondent_count} responden</Text></Card>):<Notice>Belum ada hasil {type}.</Notice>}</Screen>}
export function ComparisonScreen(){const q=useQuery({queryKey:['comparison'],queryFn:()=>api<any[]>('/researcher/results/comparison')});return <Screen><Title subtitle="Perbandingan responden dengan pasangan nilai tersedia.">Pretest vs Posttest</Title>{q.isLoading?<Loading/>:q.error?<Notice>{q.error.message}</Notice>:q.data?.map(v=><Card key={v.video_id}><Text style={s.cardTitle}>Video {v.sequence_number}: {v.title}</Text><Metric label="Rata-rata pretest" value={v.average_pretest??0}/><Metric label="Rata-rata posttest" value={v.average_posttest??0}/><Metric label="Selisih" value={v.difference??0}/><Text style={[s.improvement,{color:Number(v.improvement_percentage)>=0?colors.success:colors.danger}]}>{v.improvement_percentage==null?'Belum cukup data':`${v.improvement_percentage}% perubahan`}</Text><Text style={ui.muted}>{v.paired_respondents} pasangan data</Text></Card>)}</Screen>}

export function ExportScreen(){const[type,setType]=useState('full_dataset');const[dateFrom,setFrom]=useState('');const[dateTo,setTo]=useState('');const[videoNumber,setVideo]=useState('');const[status,setStatus]=useState('');const[busy,setBusy]=useState(false);async function run(){try{setBusy(true);const token=useSession.getState().token;const response=await fetch(`${process.env.EXPO_PUBLIC_API_BASE_URL}/researcher/export`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({exportType:type,dateFrom:dateFrom||undefined,dateTo:dateTo||undefined,videoNumber:videoNumber?Number(videoNumber):undefined,status:status||undefined})});if(!response.ok){const body=await response.json();throw new Error(body.error?.message??'Ekspor gagal.')}const csv=await response.text();const uri=`${FileSystem.cacheDirectory}siaga-bunda-${Date.now()}.csv`;await FileSystem.writeAsStringAsync(uri,csv,{encoding:FileSystem.EncodingType.UTF8});if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType:'text/csv',dialogTitle:'Bagikan data penelitian'});else Alert.alert('Ekspor selesai',uri)}catch(e){Alert.alert('Ekspor gagal',e instanceof Error?e.message:'Coba kembali.')}finally{setBusy(false)}}return <Screen><Title subtitle="Ekspor menggunakan kode responden anonim dan dicatat dalam audit.">Ekspor Data</Title><Text style={ui.label}>Jenis data</Text>{['full_dataset','respondent_data','video_progress','pretest','posttest'].map(item=><Pressable key={item} style={[s.choice,type===item&&s.choiceActive]} onPress={()=>setType(item)}><Text style={ui.label}>{item.replaceAll('_',' ')}</Text></Pressable>)}<Field label="Nomor video 1–7 (opsional)" value={videoNumber} onChangeText={setVideo} keyboardType="number-pad"/><Field label="Status video (opsional)" value={status} onChangeText={setStatus} placeholder="completed"/><Field label="Tanggal mulai (YYYY-MM-DD, opsional)" value={dateFrom} onChangeText={setFrom}/><Field label="Tanggal akhir (YYYY-MM-DD, opsional)" value={dateTo} onChangeText={setTo}/><Notice>File CSV kompatibel dengan Excel. Identitas langsung tidak disertakan pada ekspor standar.</Notice><Button disabled={busy} onPress={run}>{busy?'Membuat file…':'Buat dan Bagikan CSV'}</Button></Screen>}

const date=(v:string)=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(`${v}T00:00:00`));const dateTime=(v:string)=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));const statusLabel=(v:string)=>({pretest_required:'Pretest diperlukan',video_available:'Video tersedia',video_in_progress:'Video berlangsung',waiting_posttest:'Menunggu posttest',posttest_available:'Posttest tersedia',completed:'Selesai',locked:'Terkunci'}[v]??v);
const s=StyleSheet.create({grid:{flexDirection:'row',flexWrap:'wrap',gap:10},summary:{width:'48%',minHeight:115,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:18,padding:15,justifyContent:'center'},value:{fontSize:28,fontWeight:'900',color:colors.primaryDark},cardTitle:{fontSize:17,fontWeight:'800',color:colors.text},score:{fontSize:34,fontWeight:'900',color:colors.primary},timeline:{flexDirection:'row',gap:12},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.primary,marginTop:5},improvement:{fontSize:18,fontWeight:'900'},filter:{paddingHorizontal:12,paddingVertical:9,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},choice:{padding:14,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},choiceActive:{borderColor:colors.primary,backgroundColor:colors.pink}});
