import { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, AppState, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useVideoPlayer, VideoView } from 'expo-video';
import type { Question, VideoStatus } from '@siaga/shared';
import { api, post } from '../../services/api'; import { useSession } from '../../services/session'; import { Badge, Button, Card, Field, Loading, Notice, Progress, Screen, Title, ui } from '../../components/ui'; import { colors } from '../../theme';

type Video={id:string;sequence_number:number;title:string;description:string;video_url:string;duration_seconds:number;status:VideoStatus;completion_percentage:number;max_watched_seconds:number;available_at?:string};
const labels:Record<VideoStatus,string>={locked:'Terkunci',pretest_required:'Isi pretest',video_available:'Video tersedia',video_in_progress:'Lanjutkan video',waiting_posttest:'Menunggu posttest',posttest_available:'Isi posttest',completed:'Selesai'};
const tones=(s:VideoStatus)=>s==='completed'?'success':s==='locked'?'neutral':s==='waiting_posttest'?'warning':'neutral';

export function DashboardScreen(){const qc=useQueryClient();const profile=useQuery({queryKey:['profile'],queryFn:()=>api<any>('/respondents/me')});const videos=useQuery({queryKey:['videos'],queryFn:()=>api<Video[]>('/videos')});if(profile.isLoading||videos.isLoading)return <Screen><Loading/></Screen>;if(profile.error||videos.error)return <Screen><Notice action={<Button onPress={()=>{profile.refetch();videos.refetch()}}>Coba lagi</Button>}>{(profile.error??videos.error)?.message}</Notice></Screen>;const list=videos.data??[];const pct=list.length?list.filter(v=>v.status==='completed').length/list.length*100:0;const next=list.find(v=>v.status!=='completed'&&v.status!=='locked');return <Screen><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Title subtitle={`Usia kehamilan ${profile.data.pregnancy_age_weeks} minggu • HPL ${formatDate(profile.data.hpl)}`}>Halo, Ibu {profile.data.name.split(' ')[0]}</Title><Pressable onPress={()=>router.push('/respondent/profile' as never)}><Text style={s.profile}>Profil</Text></Pressable></View><Card><Text style={s.cardTitle}>Progres edukasi</Text><Progress value={pct}/><Text style={ui.muted}>{Math.round(pct)}% • {list.filter(v=>v.status==='completed').length} dari {list.length} video selesai</Text>{next&&<Text style={s.next}>Berikutnya: {labels[next.status]} Video {next.sequence_number}</Text>}</Card><Title>Materi Edukasi</Title>{list.map(v=><Card key={v.id} onPress={()=>{if(v.status==='locked')Alert.alert('Video terkunci','Selesaikan posttest video sebelumnya terlebih dahulu.');else router.push(`/respondent/videos/${v.id}` as never)}}><View style={{flexDirection:'row',gap:12}}><View style={s.number}><Text style={s.numberText}>{v.sequence_number}</Text></View><View style={{flex:1,gap:7}}><Text style={s.cardTitle}>{v.title}</Text><Badge tone={tones(v.status)}>{labels[v.status]}</Badge>{v.status==='waiting_posttest'&&v.available_at&&<Text style={ui.muted}>Tersedia {formatDateTime(v.available_at)}</Text>}<Progress value={v.completion_percentage}/></View></View></Card>)}<Button variant="secondary" onPress={()=>qc.invalidateQueries()}>Perbarui status</Button></Screen>}

export function ProfileScreen(){const q=useQuery({queryKey:['profile'],queryFn:()=>api<any>('/respondents/me')});if(q.isLoading)return <Screen><Loading/></Screen>;if(!q.data)return <Screen><Notice>Profil tidak ditemukan.</Notice></Screen>;const p=q.data;return <Screen><Title subtitle="Data hanya dapat diubah untuk bidang aman pada MVP.">Profil Ibu</Title><Card>{[['Nama',p.name],['Usia',`${p.age} tahun`],['Telepon',p.phone_number],['Alamat',p.address],['Pendidikan',p.education],['Pekerjaan',p.occupation]].map(([a,b])=><Row key={a} label={a} value={b}/>)}</Card><Title>Kehamilan</Title><Card>{[['HPHT',formatDate(p.hpht)],['HPL',formatDate(p.hpl)],['Usia kehamilan',`${p.pregnancy_age_weeks} minggu`],['Jumlah anak',String(p.number_of_children)],['Riwayat kesehatan',p.medical_history||'Tidak ada'],['Riwayat persalinan',p.birth_history||'Tidak ada'],['Dukungan keluarga',p.husband_support?'Ada':'Tidak ada'],['Riwayat komplikasi',p.pregnancy_complication_history||'Tidak ada']].map(([a,b])=><Row key={a} label={a} value={b}/>)}</Card><Button variant="danger" onPress={async()=>{await useSession.getState().signOut();router.replace('/onboarding' as never)}}>Keluar</Button></Screen>}
function Row({label,value}:{label:string;value:string}){return <View style={{gap:2}}><Text style={ui.label}>{label}</Text><Text style={ui.muted}>{value}</Text></View>}

export function VideoEntryScreen(){const{id}=useLocalSearchParams<{id:string}>();const q=useQuery({queryKey:['video',id],queryFn:()=>api<any>(`/videos/${id}`)});useEffect(()=>{const status=q.data?.progress?.status as VideoStatus|undefined;if(!status)return;const path=status==='pretest_required'?'pretest-intro':status==='video_available'||status==='video_in_progress'?'video-player':status==='posttest_available'?'posttest-intro':status==='completed'?'posttest-completed':'video-completed';router.replace(`/respondent/videos/${id}/${path}` as never)},[id,q.data]);return <Screen><Loading/></Screen>}

export function TestIntroScreen({type}:{type:'pretest'|'posttest'}){const{id}=useLocalSearchParams<{id:string}>();return <Screen><Title subtitle={type==='pretest'?'Jawab 10 pertanyaan sebelum menonton video.':'Jawab 10 pertanyaan untuk menyelesaikan materi ini.'}>{type==='pretest'?'Pretest':'Posttest'}</Title><Card><Text style={s.icon}>✓</Text><Text style={s.cardTitle}>Petunjuk</Text><Text style={ui.muted}>Pilih satu jawaban untuk setiap pertanyaan. Nilai dihitung oleh sistem setelah semua jawaban dikirim.</Text></Card><Notice>{type==='posttest'?'Posttest hanya dapat dibuka sesuai jadwal tujuh hari setelah video selesai.':'Video akan terbuka setelah pretest dikirim.'}</Notice><Button onPress={()=>router.push(`/respondent/videos/${id}/${type}` as never)}>Mulai {type}</Button></Screen>}

export function TestScreen({type}:{type:'pretest'|'posttest'}){const{id}=useLocalSearchParams<{id:string}>();const qc=useQueryClient();const q=useQuery({queryKey:['questions',id,type],queryFn:()=>api<Question[]>(`/videos/${id}/${type}`)});const[answers,setAnswers]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);if(q.isLoading)return <Screen><Loading/></Screen>;if(q.error)return <Screen><Notice action={<Button onPress={()=>q.refetch()}>Coba lagi</Button>}>{q.error.message}</Notice></Screen>;const questions=q.data??[];async function submit(){if(Object.keys(answers).length!==questions.length)return Alert.alert('Belum lengkap','Jawab semua pertanyaan sebelum mengirim.');try{setBusy(true);const result=await post<{score:number;correctCount:number;totalQuestions:number}>(`/videos/${id}/${type}/submit`,{answers:questions.map(question=>({questionId:question.id,selectedAnswer:answers[question.id]}))});await qc.invalidateQueries();Alert.alert(`${type==='pretest'?'Pretest':'Posttest'} selesai`,`Nilai Anda: ${result.score}`, [{text:'Lanjutkan',onPress:()=>router.replace(type==='pretest'?`/respondent/videos/${id}/video-player` as never:`/respondent/videos/${id}/posttest-completed` as never)}])}catch(e){Alert.alert('Tidak dapat mengirim',e instanceof Error?e.message:'Coba kembali.')}finally{setBusy(false)}}return <Screen><Title subtitle={`${Object.keys(answers).length} dari ${questions.length} dijawab`}>{type==='pretest'?'Pretest':'Posttest'}</Title><Progress value={Object.keys(answers).length/questions.length*100}/>{questions.map((question,index)=><Card key={question.id}><Text style={s.cardTitle}>{index+1}. {question.questionText}</Text>{Object.entries(question.options).map(([key,value])=><Pressable accessibilityRole="radio" accessibilityState={{checked:answers[question.id]===key}} key={key} style={[s.option,answers[question.id]===key&&s.optionSelected]} onPress={()=>setAnswers(a=>({...a,[question.id]:key}))}><Text style={s.optionLetter}>{key.toUpperCase()}</Text><Text style={{flex:1}}>{value}</Text></Pressable>)}</Card>)}<Button disabled={busy} onPress={submit}>{busy?'Mengirim…':'Kirim Jawaban'}</Button></Screen>}

export function VideoPlayerScreen(){const{id}=useLocalSearchParams<{id:string}>();const qc=useQueryClient();const q=useQuery({queryKey:['video',id],queryFn:()=>api<any>(`/videos/${id}`)});if(q.isLoading)return <Screen><Loading/></Screen>;if(q.error||!q.data)return <Screen><Notice>{q.error?.message??'Video tidak ditemukan.'}</Notice></Screen>;return <Player video={q.data} onDone={async()=>{await qc.invalidateQueries();router.replace(`/respondent/videos/${id}/video-completed` as never)}}/>}
function Player({video,onDone}:{video:any;onDone:()=>void}){const player=useVideoPlayer(video.video_url,p=>{p.timeUpdateEventInterval=1});const[max,setMax]=useState(Number(video.progress.max_watched_seconds??0));const[watched,setWatched]=useState(Number(video.progress.duration_watched_seconds??0));const[playing,setPlaying]=useState(false);const[busy,setBusy]=useState(false);const maxRef=useRef(max);const watchedRef=useRef(watched);const playingRef=useRef(false);const last=useRef(0);const checkpoint=()=>post(`/videos/${video.id}/progress`,{currentSecond:player.currentTime,maxWatchedSecond:maxRef.current,durationWatchedSeconds:watchedRef.current});useEffect(()=>{player.currentTime=max;post(`/videos/${video.id}/start`).catch(e=>Alert.alert('Video belum dapat dimulai',e.message));const sub=player.addListener('timeUpdate',({currentTime})=>{if(currentTime>maxRef.current+2){player.currentTime=maxRef.current;return}if(playingRef.current&&currentTime>=last.current&&currentTime-last.current<=2){watchedRef.current=Math.min(video.duration_seconds,watchedRef.current+(currentTime-last.current));setWatched(watchedRef.current)}if(currentTime>maxRef.current){maxRef.current=currentTime;setMax(currentTime)}last.current=currentTime});return()=>sub.remove()},[player,video.id]);useEffect(()=>{const timer=setInterval(()=>{if(playingRef.current)checkpoint().catch(()=>{})},10000);const state=AppState.addEventListener('change',next=>{if(next!=='active'&&playingRef.current){player.pause();playingRef.current=false;setPlaying(false);checkpoint().catch(()=>{})}});return()=>{clearInterval(timer);state.remove();checkpoint().catch(()=>{})}},[player,video.id]);async function toggle(){if(playing){player.pause();playingRef.current=false;setPlaying(false);await checkpoint().catch(()=>{})}else{player.play();playingRef.current=true;setPlaying(true)}}async function finish(){try{setBusy(true);await checkpoint();await post(`/videos/${video.id}/complete`);onDone()}catch(e){Alert.alert('Video belum selesai',e instanceof Error?e.message:'Tonton hingga akhir.')}finally{setBusy(false)}}const completed=max>=video.duration_seconds-2&&watched>=video.duration_seconds*.9;return <Screen><Title subtitle="Video tidak dapat dimajukan. Anda dapat menjeda atau mengulang bagian yang sudah ditonton.">{video.title}</Title><VideoView player={player} style={s.video} nativeControls={false} contentFit="contain"/><Progress value={max/video.duration_seconds*100}/><Text style={ui.muted}>{Math.floor(max)} / {video.duration_seconds} detik • waktu ditonton {Math.floor(watched)} detik</Text><View style={{flexDirection:'row',gap:10}}><View style={{flex:1}}><Button variant="secondary" onPress={()=>{player.currentTime=Math.max(0,player.currentTime-10)}}>−10 detik</Button></View><View style={{flex:1}}><Button onPress={toggle}>{playing?'Jeda':'Putar'}</Button></View></View><Button disabled={!completed||busy} onPress={finish}>{busy?'Menyimpan…':completed?'Selesaikan Video':'Tonton sampai selesai'}</Button></Screen>}

export function VideoCompletedScreen(){const{id}=useLocalSearchParams<{id:string}>();const q=useQuery({queryKey:['video',id],queryFn:()=>api<any>(`/videos/${id}`)});const available=q.data?.progress?.available_at;return <Screen><Title>Video Selesai</Title><Card><Text style={s.icon}>♡</Text><Text style={[s.cardTitle,{textAlign:'center'}]}>Terima kasih sudah menonton sampai selesai.</Text><Text style={[ui.muted,{textAlign:'center'}]}>{available?`Posttest tersedia pada ${formatDateTime(available)}.`:'Jadwal posttest sedang disiapkan.'}</Text></Card><Notice>Video berikutnya terbuka setelah posttest materi ini selesai.</Notice><Button onPress={()=>router.replace('/respondent/dashboard' as never)}>Kembali ke Beranda</Button></Screen>}
export function PosttestCompletedScreen(){return <Screen><Title>Materi Selesai</Title><Card><Text style={s.icon}>✓</Text><Text style={[s.cardTitle,{textAlign:'center'}]}>Posttest berhasil dikirim.</Text><Text style={[ui.muted,{textAlign:'center'}]}>Materi berikutnya kini sudah terbuka. Hebat, lanjutkan sesuai waktu Ibu.</Text></Card><Button onPress={()=>router.replace('/respondent/dashboard' as never)}>Lihat Materi Berikutnya</Button></Screen>}

const formatDate=(v:string)=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(`${v}T00:00:00`));const formatDateTime=(v:string)=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));
const s=StyleSheet.create({profile:{fontWeight:'800',color:colors.primary},cardTitle:{fontSize:17,fontWeight:'800',color:colors.text},next:{fontWeight:'700',color:colors.primaryDark},number:{width:42,height:42,borderRadius:21,backgroundColor:colors.pink,alignItems:'center',justifyContent:'center'},numberText:{fontWeight:'900',fontSize:18,color:colors.primaryDark},icon:{fontSize:58,color:colors.primary,textAlign:'center'},option:{flexDirection:'row',alignItems:'center',gap:10,padding:12,borderRadius:12,borderWidth:1,borderColor:colors.border},optionSelected:{backgroundColor:colors.pink,borderColor:colors.primary},optionLetter:{fontWeight:'900',color:colors.primaryDark},video:{width:'100%',aspectRatio:16/9,backgroundColor:'#171217',borderRadius:18}});
